// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzecRNHRY7KuT_7BkBypAaczwP8zNzHzg',
    appId: '1:43332994516:web:1fdffba3d68e784b044241',
    messagingSenderId: '43332994516',
    projectId: 'use-this-flutter-2025',
    authDomain: 'use-this-flutter-2025.firebaseapp.com',
    storageBucket: 'use-this-flutter-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD61CSCbw64hD2q6M9C04Dd-bryOYGvWGw',
    appId: '1:43332994516:android:02f269ea184b878a044241',
    messagingSenderId: '43332994516',
    projectId: 'use-this-flutter-2025',
    storageBucket: 'use-this-flutter-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClW1Tof5KEXYjhmjjrxQ8DqEm5hB7apN4',
    appId: '1:43332994516:ios:2abc06d2bf23aaf6044241',
    messagingSenderId: '43332994516',
    projectId: 'use-this-flutter-2025',
    storageBucket: 'use-this-flutter-2025.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClW1Tof5KEXYjhmjjrxQ8DqEm5hB7apN4',
    appId: '1:43332994516:ios:2abc06d2bf23aaf6044241',
    messagingSenderId: '43332994516',
    projectId: 'use-this-flutter-2025',
    storageBucket: 'use-this-flutter-2025.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzecRNHRY7KuT_7BkBypAaczwP8zNzHzg',
    appId: '1:43332994516:web:5358bf5c00f59f6b044241',
    messagingSenderId: '43332994516',
    projectId: 'use-this-flutter-2025',
    authDomain: 'use-this-flutter-2025.firebaseapp.com',
    storageBucket: 'use-this-flutter-2025.firebasestorage.app',
  );
}
